version: "3.6"

services:
    prismabenchmark:
        build:
            context: ./
            dockerfile: Dockerfile-Benchmark
        image: prismadb/prismadb-benchmark
        container_name: PrismaDB_SQL_Benchmark
        environment:
            SqlPassword: ${SqlPassword}

    prismadb:
        image: bazzilic/prismadb-mysql
        container_name: PrismaDB_SQL_Server
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "toor"

    prismaproxy:
        build:
            context: ./
            dockerfile: Dockerfile-Proxy
        image: prismadb/prismadb-mysql-proxy
        container_name: PrismaDB_SQL_Server_Proxy
        ports:
            - 4000:4000
        depends_on:
            - prismadb
        environment:
            ListenPort: "4000"
            ServerAddress: "prismadb"
            ServerPort: "3306"
            Database: "testdb"
