version: '3.6'

services:

    prismabenchmark:
        build:
            context: ./
            dockerfile: Dockerfile-Benchmark
        image: aprismatic.azurecr.io/prismadb-benchmark:alpine
        container_name: PrismaDB_SQL_Benchmark
        networks:
            - prisma
        environment:
            SqlPassword: ${SqlPassword}
            BuildVersion: ${APPVEYOR_BUILD_VERSION}
            ServerType: ${ServerType}
        
    prismadb:
        image: cheziyi/mssql-server-linux-developer-fulltext:latest
        container_name: PrismaDB_SQL_Server
        networks:
            - prisma
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "saPwd123"
            ACCEPT_EULA: "Y"
        deploy:
            resources:
                reservations:
                    memory: 24G

    prismaproxy:
        image: "aprismatic.azurecr.io/prismadb-proxy-${ServerType}:alpine"
        container_name: PrismaDB_SQL_Server_Proxy
        networks:
            - prisma
        ports:
            - 4000:4000
        depends_on:
            - prismadb
        environment:
            ListenPort: "4000"
            DataSource: "prismadb"
            InitialCatalog: "testdb"
        deploy:
            resources:
                reservations:
                    cpus: '0.50'
                    memory: 24G
    
networks:
    prisma: