version: '3.6'

services:

    prismabenchmark:
        build:
            context: ./
            dockerfile: Dockerfile-Benchmark
        image: prismadb.azurecr.io/benchmark:alpine
        container_name: PrismaDB_SQL_Benchmark
        networks:
            - prisma
        environment:
            SqlPassword: ${SqlPassword}
            BuildVersion: ${BuildVersion}
            ServerType: ${ServerType}
        
    prismadb:
        image: aprismatic/mssql-server-linux-fulltext:latest
        container_name: PrismaDB_SQL_Server
        networks:
            - prisma
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "saPwd123"
            ACCEPT_EULA: "Y"

    prismaproxy:
        image: "aprismatic/prismadb-proxy-${ServerType}:alpine"
        container_name: PrismaDB_SQL_Server_Proxy
        networks:
            - prisma
        ports:
            - 4000:4000
        depends_on:
            - prismadb
        environment:
            ListenPort: "4000"
            DataSource: "prismadb"
            InitialCatalog: "testdb"
    
networks:
    prisma: