version: '3.6'

services:

    prismabenchmark:
        build:
            context: ./
            dockerfile: Dockerfile-Benchmark
        image: aprismatic.azurecr.io/prismadb-benchmark:alpine
        container_name: PrismaDB_SQL_Benchmark
        networks:
            - prisma
        environment:
            SqlPassword: ${SqlPassword}
            BuildVersion: "no-plugin"
            ServerType: ${ServerType}
        
    prismadb:
        image: aprismatic/prismadb-mysql:latest
        container_name: PrismaDB_SQL_Server
        networks:
            - prisma
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "toor"

    prismaproxy:
        image: "aprismatic.azurecr.io/prismadb-proxy-${ServerType}:alpine"
        container_name: PrismaDB_SQL_Server_Proxy
        networks:
            - prisma
        ports:
            - 4000:4000
        depends_on:
            - prismadb
        environment:
            ListenPort: "4000"
            ServerAddress: "prismadb"
            ServerPort: "3306"
            Database: "testdb"
    
networks:
    prisma: