version: '3.6'

services:

    prismabenchmark:
        build:
            context: ../publish
            dockerfile: ../ci/Dockerfile-Benchmark
        image: prismadb.azurecr.io/benchmark:alpine
        container_name: PrismaDB_Benchmark
        networks:
            - prisma
        environment:
            SqlPassword: ${BENCHMARK_DB_PASSWORD}
            BuildVersion: ${VERSION}
            ServerType: mysql
        
    prismadb:
        image: aprismatic/prismadb-mysql:latest
        container_name: PrismaDB_SQL_Server
        networks:
            - prisma
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "saPwd123"

    prismaproxy:
        image: aprismatic/prismadb-proxy-mysql:alpine
        container_name: PrismaDB_SQL_Server_Proxy
        networks:
            - prisma
        ports:
            - 4000:4000
        depends_on:
            - prismadb
        environment:
            ListenPort: "4000"
            ServerAddress: "prismadb"
            ServerPort: "3306"
            Database: "testdb"
    
networks:
    prisma: